version: '3.8'

services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - data:/app/data
    ports:
      - "8888:8888"  # JupyterLab
      - "6006:6006"  # TensorBoard
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: jupyterlab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
  data:
