apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    # Add timeout settings
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "120s"
    # Add secure connection handling
    secureJsonData:
      httpHeaderValue1: ""
